name: test
services:

#------------------------------------------------------------------------
#------------------------RECOLECCION-------------------------------------
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  api:
    build: ./recoleccion
    ports:
      - 4000:4000
    depends_on: #para que arranque despues de mongo
      - mongo

  reparto:
    build: ./recoleccion #se arranca al mismo tiempo que la api
    ports:
      - 5000:5000
    command: node reparto.js
    depends_on:
      - mongo

#------------------------------------------------------------------------
#------------------------PAGINA DE PRUEBA---------------------------------
  pagina:
    build: .
    ports: 
      - 3000:3000
    depends_on: 
      - api


#------------------------------------------------------------------------
#------------------------PROCESAMIENTO-----------------------------------
  preprocesamiento:
    build: ./procesamiento #se arranca al mismo tiempo que la api
    command: node preprocesamiento.js
    depends_on:
      - mongo
  
  procesamiento:
    build: ./procesamiento
    command: node procesamiento.js
    depends_on:
      - mongo
      - preprocesamiento

volumes:
  db: